language: go
sudo: false
go:
  - 1.7.3

script:
  - CGO_ENABLED=1 GOARCH=amd64 GOOS=linux go build -o servicecenter github.com/servicecomb/service-center

after_success:
  - bash <(curl -s https://codecov.io/bash)
