{{- if .Values.sc.deployment -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "service-center.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "service-center.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  app-config: |
    httpaddr = ${HOSTNAME}
    httpport = {{ .Values.sc.service.internalPort }}

    {{- if .Values.sc.registry.enabled }}
    self_register = 1
    {{- else }}
    self_register = 0
    {{- end }}
    registry_plugin = {{ .Values.sc.registry.type }}
    manager_name = "{{ .Values.sc.registry.name }}"
    manager_addr = "{{ .Values.sc.registry.addr }}"

    {{- if ne .Values.sc.discovery.type "local" }}
    discovery_plugin = {{ .Values.sc.discovery.type }}
    aggregate_mode = "{{ .Values.sc.discovery.aggregate }}"
    manager_cluster = "{{ .Values.sc.discovery.clusters }}"
    {{- else }}
    discovery_plugin = etcd
    {{- end }}

    ssl_mode = 0
    enable_pprof = 1
{{- end }}
{{- if .Values.frontend.deployment }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "service-center.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "service-center.name" . }}-frontend
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  app-config: |
    frontend_host_ip = ${HOSTNAME}
    frontend_host_port = {{ .Values.frontend.service.internalPort }}
    httpaddr = {{ template "service-center.fullname" . }}
    httpport = {{ .Values.sc.service.externalPort }}
{{- end }}
